version: "3.7"
services:

  eureka-server:
    image: eureka-server:1.0.0-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - skowly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    image: config-server:1.0.0-SNAPSHOT
    container_name: config-server
    hostname: config-server
    ports:
      - "8888:8888"
    networks:
      - skowly-network
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config-server-files
    volumes:
    - ./config-server-files:/config-server-files
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
      - keycloak-config:/opt/jboss/keycloak/standalone/configuration
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    networks:
      - skowly-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    image: gateway:1.0.0-SNAPSHOT
    container_name: gateway
    ports:
      - "9191:9191"
    networks:
      - skowly-network
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761
      CONFIG_SERVER_URL: http://config-server:8888
      SKOWLY_CORE_URL: http://skowly-core:8081
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      skowly-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:9191/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  skowly-ui:
    image: skowly-ui:1.0.0-SNAPSHOT
    container_name: skowly-ui
    ports:
      - "80:80"
    networks:
      - skowly-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://skowly-ui:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  skowly-core:
    image: skowly-core:1.0.0-SNAPSHOT
    container_name: skowly-core
    ports:
      - "8085:8081"
    networks:
      - skowly-network
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761
      CONFIG_SERVER_URL: http://config-server:8888
      DB_URL: jdbc:postgresql://db-skowly-core:5432/skowly_core
      DB_USER: skowly_core
      DB_PASSWORD: root
    depends_on:
      eureka-server:
        condition: service_healthy
      db-skowly-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://skowly-core:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-skowly-core:
    image: "postgres:13"
    container_name: db-skowly-core
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - skowly-core-data:/var/lib/postgresql/data
    networks:
      - skowly-network
    environment:
      POSTGRES_DB: skowly_core
      POSTGRES_USER: skowly_core
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d skowly_core -U skowly_core"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skowly-network:
    driver: bridge

volumes:
  skowly-core-data:
  keycloak-data:
  keycloak-config: