version: "3.7"
services:
  eureka:
    image: eureka:1.0
    ports:
      - "8761:8761"
  zuul:
    image: zuul:1.0
    ports:
      - "8862:8862"
    depends_on:
      - eureka
  skowly-core:
    image: skowly-core:1.0
    ports:
      - "8085:8081"
    depends_on:
      - db_skowly_core
  db_skowly_core:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: skowly_core
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
