version: "3.7"
services:

  eureka-server:
    image: skowly/eureka-server:1.0.0-SNAPSHOT
    container_name: eureka-server
    ports:
      - "${eureka_external_port}:${eureka_internal_port}"
    networks:
      - skowly-network
    environment:
      SERVER_PORT: ${eureka_internal_port}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:${eureka_internal_port}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    image: skowly/config-server:1.0.0-SNAPSHOT
    container_name: config-server
    hostname: config-server
    ports:
      - "${config_server_external_port}:${config_server_internal_port}"
    networks:
      - skowly-network
    environment:
      SERVER_PORT: ${config_server_internal_port}
      EUREKA_SERVER_URL: http://eureka-server:${eureka_internal_port}
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config-server-files
    volumes:
    - ./config-server-files:/config-server-files
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:${config_server_internal_port}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: skowly/keycloak:15.0.2
    container_name: keycloak
    command: ["-Djboss.socket.binding.port-offset=${keycloak_port_offset}"]
    ports:
      - "${keycloak_external_port}:${keycloak_internal_port}"
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
      - keycloak-config:/opt/jboss/keycloak/standalone/configuration
    environment:
      - KEYCLOAK_USER=${keycloak_user}
      - KEYCLOAK_PASSWORD=${keycloak_password}
      - DB_VENDOR=H2
    networks:
      - skowly-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:${keycloak_internal_port}/auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    image: skowly/gateway:1.0.0-SNAPSHOT
    container_name: gateway
    ports:
      - "${gateway_external_port}:${gateway_internal_port}"
    networks:
      - skowly-network
    environment:
      SERVER_PORT: ${gateway_internal_port}
      EUREKA_SERVER_URL: http://eureka-server:${eureka_internal_port}
      CONFIG_SERVER_URL: http://config-server:${config_server_internal_port}
      SKOWLY_CORE_URL: http://skowly-core:${skowly_core_internal_port}
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:${gateway_internal_port}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  skowly-ui:
    image: skowly/skowly-ui:1.0.0-SNAPSHOT
    container_name: skowly-ui
    ports:
      - "80:80"
    networks:
      - skowly-network
    depends_on:
      eureka-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://skowly-ui:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  skowly-core:
    image: skowly/skowly-core:1.0.0-SNAPSHOT
    container_name: skowly-core
    ports:
      - "${skowly_core_external_port}:${skowly_core_internal_port}"
    networks:
      - skowly-network
    environment:
      SERVER_PORT: ${skowly_core_internal_port}
      EUREKA_SERVER_URL: http://eureka-server:${eureka_internal_port}
      CONFIG_SERVER_URL: http://config-server:${config_server_internal_port}
      KEYCLOAK_ISSUER_URI: http://localhost/auth/realms/${keycloak_realm}
      KEYCLOAK_JWK_SET_URI: http://skowly-ui:80/auth/realms/${keycloak_realm}/protocol/openid-connect/certs
      KEYCLOAK_SERVER_URL: http://localhost/auth
      KEYCLOAK_REALM: ${keycloak_realm}
      KEYCLOAK_RESOURCE: ${keycloak_resource}
      KEYCLOAK_SECRET: ${keycloak_resource_secret}
      mail_host: ${mail_host}
      mail_port: ${mail_port}
      mail_username: ${mail_username}
      mail_password: ${mail_password}
      mail_smtp_auth: ${mail_smtp_auth}
      mail_smtp_starttls_enable: ${mail_smtp_starttls_enable}
      DB_URL: jdbc:postgresql://db-skowly-core:5432/${db_skowly_core_db}
      DB_USER: ${db_skowly_core_user}
      DB_PASSWORD: ${db_skowly_core_password}
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      db-skowly-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://skowly-core:${skowly_core_internal_port}/api/core/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-skowly-core:
    image: "postgres:13"
    container_name: db-skowly-core
    restart: always
    ports:
      - "${db_skowly_core_external_port}:5432"
    volumes:
      - skowly-core-data:/var/lib/postgresql/data
    networks:
      - skowly-network
    environment:
      POSTGRES_DB: ${db_skowly_core_db}
      POSTGRES_USER: ${db_skowly_core_user}
      POSTGRES_PASSWORD: ${db_skowly_core_password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${db_skowly_core_db} -U ${db_skowly_core_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      #smtp port
      - "1025:1025"
      # http port
      - "8025:8025"
    networks:
      - skowly-network

networks:
  skowly-network:
    driver: bridge

volumes:
  skowly-core-data:
  keycloak-data:
  keycloak-config: