version: "3.7"
services:

  eureka:
    image: eureka:1.0
    ports:
      - "8761:8761"
    networks:
      - skowly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  zuul:
    image: zuul:1.0
    ports:
      - "8862:8862"
    networks:
      - skowly-network
    depends_on:
      eureka:
        condition: service_healthy
      skowly-ui:
        condition: service_healthy
      skowly-core:
        condition: service_healthy
      
  skowly-ui:
    image: skowly-ui:1.0
    ports:
      - "4202:4200"
    networks:
      - skowly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  skowly-core:
    image: skowly-core:1.0
    ports:
      - "8085:8081"
    networks:
      - skowly-network
    depends_on:
      db_skowly_core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  db_skowly_core:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - skowly_core-data:/var/lib/mysql
    networks:
      - skowly-network
    environment:
      MYSQL_DATABASE: skowly_core
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  skowly-network:
    driver: bridge
    
volumes:
  skowly_core-data:
