name: Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test-config-server:
    runs-on: windows-latest

    if: ${{ contains(github.event.head_commit.added, 'config-server/') || contains(github.event.head_commit.modified, 'config-server/') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test config-server
      run: |
        cd config-server
        .\mvnw clean package
        .\mvnw test

  build-and-test-eureka-server:
    runs-on: windows-latest

    if: ${{ contains(github.event.head_commit.added, 'eureka-server/') || contains(github.event.head_commit.modified, 'eureka-server/') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test eureka-server
      run: |
        cd eureka-server
        .\mvnw clean package
        .\mvnw test

  build-and-test-gateway:
    runs-on: windows-latest

    if: ${{ contains(github.event.head_commit.added, 'gateway/') || contains(github.event.head_commit.modified, 'gateway/') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test gateway
      run: |
        cd gateway
        .\mvnw clean package
        .\mvnw test

  build-and-test-skowly-core:
    runs-on: windows-latest

    if: ${{ contains(github.event.head_commit.added, 'skowly-core/') || contains(github.event.head_commit.modified, 'skowly-core/') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test skowly-core
      run: |
        cd skowly-core
        .\mvnw clean package
        .\mvnw test

  build-and-test-skowly-ui:
    runs-on: windows-latest

    if: ${{ contains(github.event.head_commit.added, 'skowly-ui/') || contains(github.event.head_commit.modified, 'skowly-ui/') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test skowly-ui
      run: |
        cd skowly-ui
        npm install
        npm run test
