name: Build and Deploy Skowly Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Maven
        run: |
          cd skowly-core
          mvn clean verify

      - name: Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: SpringBoot Report
          path: skowly-core/target/site/serenity/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and switch to the gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git push origin gh-pages

      - name: Copy the artifact to the root of the gh-pages branch
        run: |
          cp -r skowly-core/target/site/serenity $GITHUB_WORKSPACE
          git add -A
          git commit -m "Deploying the artifact to GitHub Pages"
          git push origin gh-pages

