name: Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test-config-server:
    name: Build and Test Config Server
    runs-on: windows-latest

    if: |
      contains(github.event.commits[0].added, 'config-server/') || 
      contains(github.event.commits[0].modified, 'config-server/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test config-server
      run: |
        cd config-server
        .\mvnw clean package
        .\mvnw test

  build-and-test-eureka-server:
    name: Build and Test Eureka Server
    runs-on: windows-latest

    if: |
      contains(github.event.commits[0].added, 'eureka-server/') || 
      contains(github.event.commits[0].modified, 'eureka-server/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test eureka-server
      run: |
        cd eureka-server
        .\mvnw clean package
        .\mvnw test

  build-and-test-gateway:
    name: Build and Test Gateway
    runs-on: windows-latest

    if: |
      contains(github.event.commits[0].added, 'gateway/') || 
      contains(github.event.commits[0].modified, 'gateway/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test gateway
      run: |
        cd gateway
        .\mvnw clean package
        .\mvnw test

  build-and-test-skowly-core:
    name: Build and Test Skowly Core
    runs-on: windows-latest

    if: |
      contains(github.event.commits[0].added, 'skowly-core/') || 
      contains(github.event.commits[0].modified, 'skowly-core/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test skowly-core
      run: |
        cd skowly-core
        .\mvnw clean package
        .\mvnw test

  build-and-test-skowly-ui:
    name: Build and Test Skowly UI
    runs-on: windows-latest

    if: |
      contains(github.event.commits[0].added, 'skowly-ui/') || 
      contains(github.event.commits[0].modified, 'skowly-ui/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test skowly-ui
      run: |
        cd skowly-ui
        npm install
        npm run test
