name: Skowly CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        .\build.bat -skipDocker all
      shell: powershell # Use PowerShell to run the batch script

