name: Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        config-server: ['config-server/']
        eureka-server: ['eureka-server/']
        gateway: ['gateway/']
        skowly-core: ['skowly-core/']
        skowly-ui: ['skowly-ui/']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test
      run: |
        microservice=${{ matrix.key }}
        cd $microservice
        .\mvnw clean package
        .\mvnw test

    - name: Build and test skowly-ui
      run: |
        microservice=${{ matrix.key }}
        if [[ $microservice == 'skowly-ui/' ]]; then
          cd $microservice
          npm install
          npm run test
        fi
