name: Skowly CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        config-server: ['config-server/']
        eureka-server: ['eureka-server/']
        gateway: ['gateway/']
        skowly-core: ['skowly-core/']
        skowly-ui: ['skowly-ui/']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test
      run: |
        $microservice = "${{ matrix.config-server || matrix.eureka-server || matrix.gateway || matrix.skowly-core || matrix.skowly-ui }}"
        if ($microservice) {
          Write-Host "Running build and test for $microservice"
          cd $microservice
          .\mvnw clean package
          .\mvnw test
        } else {
          Write-Host "No changes detected in microservices. Skipping build and test."
        }
