name: Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build and test config-server
      run: |
        cd config-server
        ./mvnw clean package
        ./mvnw test

    - name: Build and test eureka-server
      run: |
        cd eureka-server
        ./mvnw clean package
        ./mvnw test

    - name: Build and test gateway
      run: |
        cd gateway
        ./mvnw clean package
        ./mvnw test

    - name: Build and test skowly-core
      run: |
        cd skowly-core
        ./mvnw clean package
        ./mvnw test

    - name: Build and test skowly-ui
      run: |
        cd skowly-ui
        npm install
        ng test

  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v1
