name: Skowly Core
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment Version and Commit
        run: |
          # Increment the version in Maven POM files using the Versions Maven Plugin
          mvn versions:set -DnewVersion=increment

          # Commit the changes
          git config user.name "dhiasaadlaui"
          git config user.email "dhiasaadlaui@gmail.com"
          git commit -am "Increment version"

      - name: Push changes
        run: git push origin main -u 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
  skowly-core:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: run maven test
      run: cd skowly-core && mvn clean verify install
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: skowly-core-artifacts
        path: skowly-core/target/*.jar
  eureka-server:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run maven test
      run: cd eureka-server && mvn clean verify install
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: eureka-server-artifacts
        path: eureka-server/target/*.jar
  gateway:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run maven test
      run: cd gateway && mvn clean verify install
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: gateway-artifacts
        path: gateway/target/*.jar

  config-server:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run maven test
      run: cd config-server && mvn clean verify install
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: config-server-artifacts
        path: config-server/target/*.jar
