name: Skowly Core
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  skowly-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: run maven test
      run: cd skowly-core && mvn clean verify install
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: skowly-core-artifacts
        path: skowly-core/target/*.jar
  eureka-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run maven test
      run: cd eureka-server && mvn clean verify
    - name: Publish Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: eureka-server-artifacts
        path: eureka-server/target/*.jar
