name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  build_projects:
    name: Build Projects
    needs: build_common
    runs-on: ubuntu-latest

    steps:
      - name: Conditional Checkout and Build Skowly Core
        if: ${{ github.event.head_commit.modified | contains('skowly-core/') }}
        run: |
          cd skowly-core
          mvn clean verify

      - name: Conditional Checkout and Build Eureka Server
        if: ${{ github.event.head_commit.modified | contains('eureka-server/') }}
        run: |
          cd eureka-server
          mvn clean verify
