name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  skowly_core_build:
    name: Build Skowly Core
    needs: build_common
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.modified | contains('skowly-core/') }}

    steps:
      - name: Build with Maven
        run: cd skowly-core && mvn clean verify

  eureka_server_build:
    name: Build Eureka Server
    needs: build_common
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.modified | contains('eureka-server/') }}

    steps:
      - name: Build with Maven
        run: cd eureka-server && mvn clean verify
